import React from 'react';
import WavescrollbarReact from './wavescrollbar-react'
function App() {
   return (

      <>

         <WavescrollbarReact setAnimation setGradient setTransition >
         </WavescrollbarReact>

         <p className="container">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos atque et velit doloremque iusto sunt labore veniam accusamus, aut ipsam quam, saepe quidem dolorum error ducimus earum rerum. Earum, ipsam.
            Laborum quos ex quia quae, quo sed placeat, totam omnis obcaecati, id exercitationem pariatur explicabo nostrum praesentium! Explicabo cumque quae, temporibus voluptatibus unde nesciunt repellat aperiam enim odio rerum ullam.
            Quam sit voluptate odio beatae earum corrupti ducimus, autem numquam ea assumenda voluptatum fugit cupiditate vitae. At delectus quo, optio laborum exercitationem unde nulla reiciendis ducimus inventore expedita. Recusandae, fugiat.
            Ea amet aliquam, libero cum, obcaecati quasi eveniet quia tempore omnis ratione corrupti consequuntur laudantium deserunt. Enim consectetur eligendi nisi neque reprehenderit necessitatibus magnam aspernatur? Id recusandae culpa possimus assumenda?
            Facilis exercitationem corrupti recusandae explicabo ipsam incidunt voluptatem tempore dolores voluptate minus deleniti odit commodi repellat dignissimos ducimus ex saepe debitis delectus cumque, dolor id? Ex illo autem quod asperiores.
            Soluta nam inventore nulla. Cumque asperiores iste, rem ullam perferendis sunt dolorem. Explicabo, quis temporibus? Hic, ut nemo accusantium consectetur libero accusamus laboriosam repudiandae eligendi architecto fugiat blanditiis itaque esse?
            Odit molestiae, modi excepturi, obcaecati quos iusto vero facere hic libero magnam, accusantium eveniet consequuntur sequi iste sed delectus earum qui dicta voluptatem quisquam? Itaque esse saepe doloremque molestias obcaecati.
            Fugit ipsa dicta atque enim expedita adipisci veritatis molestias officiis dolorem aut, assumenda sapiente asperiores alias deleniti corporis aperiam incidunt at maxime officia modi quia? Aperiam quaerat earum ad maxime.
            Veniam, nemo? Eos dicta, numquam nihil deserunt a ducimus officia suscipit fugiat ratione temporibus accusamus accusantium enim placeat cum ab necessitatibus porro doloribus non dolor eaque architecto magnam adipisci consequatur.
            Enim vero nulla, unde dolore a ipsum aliquam magni ipsa consectetur suscipit quas quidem amet distinctio adipisci harum nesciunt eum dicta expedita earum voluptate non voluptatum. Corrupti ipsam dolorem minima?
            Quos explicabo enim ipsum voluptate similique quasi sequi aliquid facere, delectus repudiandae illo odio repellendus deleniti ipsam vitae nesciunt officiis autem. Ducimus eius, perspiciatis fuga delectus nihil quisquam laudantium dignissimos?
            Tenetur accusamus nostrum repudiandae veritatis, alias aut totam eveniet voluptatem illum quas ipsum at dignissimos voluptatibus tempora quod sit corrupti harum quisquam nam placeat. Tempore delectus corporis explicabo possimus laborum.
            Quod soluta facere aperiam reiciendis non iure dolor aliquam aspernatur. Accusantium maxime magnam aspernatur asperiores. Obcaecati, reprehenderit voluptatum saepe, labore amet ratione totam ex omnis, alias magni harum voluptates nisi!
            Veniam odio, cupiditate nihil eveniet maiores modi quae tenetur reprehenderit. Praesentium mollitia repudiandae dolores aut maiores quibusdam numquam, nesciunt, dolorum veniam atque rem, optio obcaecati corporis fuga quidem magni aperiam.
            Praesentium expedita consequuntur quis accusamus facere ducimus fugiat natus ea similique! Voluptate, omnis amet? Ipsam provident quas nihil. Est laudantium quis nisi voluptates illum tempore officiis laboriosam reiciendis at animi.
            Aut numquam impedit sit architecto, tempora ut iusto. Expedita eum sint magnam perferendis alias nihil optio architecto provident accusamus, ratione vel, numquam nulla, et quam ex dignissimos debitis assumenda suscipit!
            Voluptate porro quo aperiam nihil cumque alias deleniti, fugit, consequatur tempore aut animi corporis ea. Voluptatibus alias dolorem optio molestiae debitis illo quod consequatur perferendis, ex voluptates repudiandae itaque distinctio?
            Perferendis, deleniti iusto. Nostrum magnam commodi quidem! Repellat voluptatem dicta earum magnam quo quod suscipit at quam ipsa accusamus. Itaque possimus, modi voluptas sapiente ducimus nam odio ullam omnis quibusdam.
            Veniam explicabo delectus libero quis fugiat quo maxime impedit rem distinctio. Numquam culpa unde veniam vel veritatis. Placeat quo sed, quam officia molestias alias laudantium esse illum fugit ab repudiandae.
            Exercitationem, suscipit quisquam. Facilis sequi in ab officia ratione vero dolorem optio fugiat delectus impedit soluta reiciendis earum, alias aliquid ipsum esse adipisci fugit ducimus eius modi placeat. Veritatis, incidunt?
            Tempore, beatae dolorem! Quis blanditiis consequuntur quod ipsum. Omnis adipisci accusamus, eum aut at placeat vero voluptatum pariatur fugit! Voluptatum voluptates facere eaque! Quidem deleniti quasi iure accusantium sequi vel.
            Dignissimos ducimus quae nesciunt necessitatibus quis, beatae laudantium, nulla optio praesentium vero alias ad tempore rem provident pariatur nobis illo, incidunt asperiores odio quam quisquam officiis magni. Quod, saepe corporis.
            Sint a incidunt quo ullam iure optio dicta inventore dolores praesentium error. Odio fugit corrupti nam placeat asperiores quisquam labore dolore! Sunt animi, vel cupiditate obcaecati eveniet debitis corporis adipisci.
            Cumque, nobis deleniti voluptatem ea perspiciatis impedit aliquid repellat ipsa inventore culpa alias eum voluptatum magni eveniet placeat molestiae porro harum laborum illo iure hic doloribus explicabo eius possimus? Earum.
            Quas non fugit accusamus, nostrum esse illum vero iste libero natus aliquid fugiat obcaecati qui. Perspiciatis error magni fuga. Officiis deserunt distinctio sapiente atque et ipsum iste consectetur beatae corporis.
            Totam, nulla fuga. Saepe consequatur eos eius quam recusandae iusto hic! Voluptates hic rerum officia deserunt eligendi itaque quas quia repellendus in, laborum, architecto earum maiores cupiditate eveniet illo excepturi.
            Vitae temporibus, ab beatae dicta fuga illo facilis ea blanditiis, iusto quos numquam sequi, tempora harum minima sunt ipsum? Sapiente ex molestiae illo quia at doloribus reprehenderit repudiandae delectus facilis!
            Placeat vero architecto ipsam nulla excepturi sed quia harum fugit eveniet quaerat ipsa quisquam deleniti sit voluptatum cupiditate nam, eum incidunt blanditiis, aliquid quis similique. Iusto cupiditate quas quidem incidunt?
            Recusandae quasi, et eveniet, distinctio perferendis dolorum excepturi non quos quae magni quibusdam consequatur itaque modi saepe omnis dolorem consectetur rerum fuga molestias alias exercitationem. Modi harum nobis ea ipsam.
            Iusto, iure impedit. Hic nesciunt consequatur vel. Et repellat eveniet quis amet, pariatur adipisci quibusdam provident laborum commodi est consequuntur a officia. Temporibus perspiciatis voluptatem earum modi accusamus quasi quaerat.
            Nihil tempora cum sit. Illum, voluptas, cupiditate dolor inventore beatae vero sint officiis voluptates mollitia, expedita rem suscipit laborum at dolores veritatis aliquid repudiandae praesentium dicta ab dignissimos modi esse.
            Omnis quis suscipit voluptatum neque, obcaecati dignissimos fugiat totam minus enim cum, inventore error? Ex culpa necessitatibus odio ea quibusdam esse praesentium sed tempora ratione itaque doloribus iusto, unde similique?
            Alias reiciendis quibusdam cumque rem nulla, incidunt architecto? Adipisci dolorem hic odio quo, culpa impedit quibusdam deleniti. Ea eius officia voluptate laudantium deserunt sit accusamus, voluptates quisquam cumque, reprehenderit nihil?
            Mollitia ullam blanditiis dolorem et quo, optio eveniet adipisci veniam debitis amet voluptatum qui sint dolor iste quae praesentium necessitatibus perspiciatis enim vero voluptas. Quasi iusto error dolorem expedita consequuntur?
            Reprehenderit adipisci enim dolorum quidem nobis eius consequuntur eligendi consectetur eum animi omnis sit quisquam vero sunt eos quae a, sequi tempora voluptas numquam facere alias incidunt. Quam, odio cumque.
            Ex velit non, pariatur maxime modi deleniti quia sapiente ad maiores ipsa dignissimos minus porro ea qui voluptates. Neque ea minus blanditiis nisi! Maiores, ratione. Alias consequatur esse sapiente laboriosam!
            Cum vitae rem nisi possimus modi inventore! Nostrum ut libero quaerat, alias aperiam facere placeat necessitatibus deserunt quidem voluptas quas aliquam architecto eos ad at minus error ducimus natus perferendis!
            Eligendi, fugiat consectetur! Officiis quisquam culpa repellendus. Quae odit voluptates deserunt hic iure. Adipisci, hic totam aut voluptate velit ipsam, quia porro id quidem quae voluptates iure labore voluptatem officia?
            Vel facere magnam libero adipisci eligendi expedita distinctio placeat iste autem accusamus recusandae cum harum tempora, quos, natus laudantium! Magnam architecto labore perferendis voluptate adipisci ratione quae reprehenderit praesentium sit?
            Facere fuga placeat velit molestiae repudiandae sint, eaque vero accusamus mollitia nihil. Aliquam labore voluptatum quo vero nesciunt cumque. Magnam, amet eos. Vitae hic consectetur laudantium itaque sed reprehenderit? Reiciendis.
            Deserunt sapiente earum quisquam nam ratione dicta commodi incidunt debitis neque autem error, ut maxime consequuntur iste officiis quo. Quisquam quos suscipit aut a delectus quo, perspiciatis minus laboriosam commodi!
            Mollitia cumque sed accusamus quaerat? Sequi, eius. Quas vitae impedit blanditiis modi corporis, obcaecati labore! Eos tempora ex, beatae laudantium laboriosam quidem atque praesentium molestias cum distinctio sapiente itaque rerum?
            In, itaque expedita accusantium voluptatibus sapiente consequuntur iste nostrum sunt tempore ipsam cumque cum, beatae sit tenetur illo labore officiis incidunt? Id fugit rem dignissimos velit enim, ratione debitis qui?
            Possimus est iusto voluptates, voluptatibus nam velit perferendis eveniet repellat? Ipsum, deleniti? Vitae expedita magnam aperiam libero fugiat suscipit ipsa veritatis, optio praesentium architecto quibusdam accusamus excepturi dicta voluptatem inventore?
            Perferendis porro soluta vitae minima, aliquid, quasi ex optio ad quod, quae hic illum! Dolorem iusto hic, recusandae quasi nihil libero vitae placeat consequuntur ducimus consequatur! Ipsum quo sint repellendus.
            Est id, natus praesentium quis cum accusantium tenetur maxime esse illum quos, nostrum placeat impedit exercitationem dolores soluta enim? Illum nisi porro similique iste minima libero delectus deleniti, ipsa aspernatur.
            Quis quibusdam dolor laudantium. Fugit eveniet, quas itaque ut consectetur assumenda nulla cumque quibusdam vitae aspernatur ab corporis perspiciatis suscipit illo consequatur exercitationem rem voluptatum eum veniam. Accusantium, molestias cum!
            Voluptate architecto culpa, ducimus quod, voluptatem repellendus placeat, aperiam aliquid labore nam accusamus dolor. Nesciunt maxime quia consectetur dicta, rem quis magnam? Sit ipsum vero voluptate officia cumque commodi quae.
            Eius omnis accusamus, molestiae facilis exercitationem aspernatur dolore eveniet temporibus, porro officiis veritatis explicabo magni natus consequatur quasi provident cum eum veniam maiores inventore harum! Optio atque deleniti incidunt quae?
            Neque praesentium consectetur sit. Perferendis hic neque sit nobis eligendi, et, rem fugit eos, in magni natus optio deserunt corporis aspernatur culpa corrupti ratione? Distinctio harum nisi illo molestiae recusandae?
            Harum sunt ducimus ipsam similique. Cumque similique aperiam nulla tenetur dolore voluptatibus animi, facere distinctio corporis aspernatur veritatis, sapiente fuga odit dignissimos non. Delectus atque vel maxime deleniti assumenda animi?
            Maiores, voluptas laudantium error officia laboriosam reiciendis dicta amet? Exercitationem aliquid voluptatibus eos alias reiciendis neque beatae, a error. Fugit eveniet quia perferendis soluta tempora ullam. Sunt earum optio id!
            Consequatur iure nam quam odio debitis adipisci, ipsam voluptatum quo cum. Ullam atque autem optio nisi fugit voluptate culpa quia explicabo eligendi excepturi cupiditate totam, voluptatem at nostrum quisquam libero!
            Incidunt harum dolor hic nostrum corrupti animi qui consectetur? Debitis eum, laboriosam, modi exercitationem quam ipsa recusandae vel veniam reiciendis dolor quia magni animi ab dicta soluta blanditiis? Animi, atque?
            Quae non eveniet, illo nobis consequuntur architecto iure saepe quas enim, voluptas odit quisquam nemo. Ad provident commodi quidem veniam possimus labore hic vero laboriosam, aliquid voluptas, quis accusantium. Sint.
            Voluptatum blanditiis architecto quae quo placeat sunt eum libero cupiditate cumque alias labore voluptates similique, magnam, ullam, optio velit? Cumque quisquam laudantium libero ut suscipit enim, ab quo optio sed!
            Omnis eaque recusandae a quasi voluptate fugiat quis consectetur unde earum accusantium quod commodi perferendis quia ipsum facilis obcaecati quidem optio, quam odit doloribus architecto. Sit enim ad necessitatibus quo?
            Deserunt, repellendus rerum! Incidunt rerum eaque distinctio illo itaque perspiciatis consequatur excepturi delectus et quo sunt ea doloremque, nemo suscipit quia, culpa nisi quibusdam! Doloremque, quae voluptas. Repudiandae, odit soluta.
            Esse, reprehenderit quas repellat veritatis eveniet nesciunt, reiciendis provident repudiandae modi distinctio adipisci laboriosam pariatur rerum autem dolore suscipit minima praesentium. Maxime autem nemo voluptate incidunt corrupti velit illo facere!
            Animi rerum adipisci quasi autem reiciendis eaque blanditiis nostrum repudiandae id vitae aliquid, sed porro facere officia, sit praesentium illum perspiciatis. Velit iure tempore architecto dicta sapiente, sit libero quaerat.
            At soluta officiis magni sapiente itaque et, ipsum accusantium, possimus suscipit voluptatibus dolorum. Doloremque, aut explicabo fugiat excepturi consequuntur vero illum similique veniam non magnam odio dolore tempora fugit quasi!
            Veritatis architecto possimus, velit unde incidunt molestiae a voluptatum eveniet, dolore eum nostrum sed deleniti harum. Odit quas aliquam voluptas animi ratione cum quos, accusamus natus voluptates dignissimos, neque soluta?
            Autem eveniet exercitationem necessitatibus voluptatem cupiditate? Excepturi reprehenderit earum reiciendis, dolorum temporibus perferendis dicta vero obcaecati voluptatem minima blanditiis ipsum laboriosam aliquam soluta ratione eligendi sed voluptatibus quas dignissimos nemo.
            Architecto ipsum consequatur nemo sint dicta delectus commodi, corporis perferendis minima dolores officia expedita sit, numquam reprehenderit libero dolorum distinctio harum cum totam ad praesentium, sed amet excepturi. Provident, fugiat!
            Distinctio fugit recusandae blanditiis. Doloribus, aperiam perspiciatis eaque in quidem repellat veniam laboriosam eius eligendi blanditiis quaerat pariatur? Fugiat animi ea natus officia sapiente blanditiis corporis voluptatibus vitae, saepe eligendi?
            Laudantium nesciunt neque incidunt doloremque eaque! Maiores animi ipsa natus, perferendis iure officia fugit quae ipsam earum sit nihil aliquam sapiente, nam non sunt distinctio, soluta tempora enim libero voluptas?
            Eius, doloremque! Tempora, laboriosam. Omnis aspernatur, pariatur deserunt iure eum corrupti eius, accusamus ipsum magni quaerat necessitatibus eaque tempora consequatur? Animi est excepturi nam soluta, quia et dicta sed ab!
            Animi deleniti error facilis, voluptates vel necessitatibus inventore consectetur at quo, voluptatibus laborum sint exercitationem odio labore temporibus ipsa quam repudiandae recusandae! Rerum illum fuga asperiores dolorum aspernatur, veniam ex.
            Non sint dolorum ducimus? Dolor nulla mollitia molestias vel esse soluta totam provident. Molestiae optio qui, molestias earum dolor, ab sint aliquid fuga, reprehenderit corporis animi vero similique doloribus dolorum!
            Libero harum ipsam nostrum cupiditate quidem, minima eum excepturi incidunt vero dolores ipsum, eaque, voluptates nam atque voluptate deleniti. Natus saepe quasi obcaecati earum ipsam dolorum officia recusandae iusto maiores!
            Architecto minus similique quam pariatur provident deleniti, mollitia magnam. Perspiciatis id corrupti error ducimus commodi? Accusantium veniam temporibus velit, earum iusto ea quam enim. Veniam ipsam ab dicta explicabo pariatur.
            Possimus in, at eos dolores quo inventore laboriosam delectus doloribus eius laborum! Quam accusamus qui expedita minus sequi delectus non magnam eveniet facere vel. Necessitatibus quidem corporis quo doloremque a.
            Dignissimos eveniet illum delectus ut sapiente velit dolorem accusantium, provident praesentium cumque veritatis modi non soluta magni aut voluptate inventore, corporis, fuga ratione cum qui voluptas. Laudantium laborum nesciunt atque.
            Distinctio nihil quae quasi accusantium magni in voluptate vitae quidem laborum consequatur fuga ullam quos, soluta culpa ipsum, incidunt quis. Soluta quos illum odio, earum deleniti minima culpa voluptatum enim!
            Ex in distinctio fugiat eveniet nemo harum, deserunt doloribus accusamus iusto nisi vitae voluptate voluptates nesciunt non numquam, et dolore minus, voluptatem ipsam libero nihil expedita. Tenetur maxime animi dignissimos!
            Animi voluptatibus molestiae fugit eligendi enim, rerum inventore numquam aspernatur velit voluptatum fugiat nostrum dolor aliquid. In nostrum voluptatem explicabo eveniet ipsa, corporis, temporibus dolore suscipit accusantium, beatae perspiciatis odio?
            Ratione aperiam aut at numquam provident ducimus similique nulla perspiciatis voluptatibus quo alias distinctio id laboriosam sequi deserunt eius qui quam sunt, earum facilis nostrum. Voluptatum quam aliquam aliquid quas.
            Quis, nulla perferendis! Impedit nihil porro quaerat laudantium suscipit blanditiis quis ut at tempora, accusantium odit labore, molestias molestiae dolores ad debitis modi accusamus? Hic dolores voluptas aliquam officia magnam!
            Sequi obcaecati maxime dolorem nulla? Corrupti maxime voluptas aut magnam natus excepturi ullam ex? Consectetur doloribus ad id eveniet illum natus. Veniam quidem aspernatur omnis iusto neque repudiandae animi quos.
            Harum vel doloremque ducimus veniam quia voluptas quidem deserunt facilis officia soluta qui vero iusto recusandae ullam laborum, in ipsum similique molestias reiciendis accusantium cum dolore nostrum aspernatur debitis. Libero.
            Quia voluptatum minus, repellendus rem cupiditate quo placeat perferendis. Earum repudiandae error ea magni enim nihil vitae quibusdam iure? Quis quam voluptates optio assumenda facere consequuntur dignissimos totam eius ducimus!
            Magni culpa libero rerum nulla delectus placeat illum ipsam distinctio, harum minima. Laudantium itaque, error fugit provident eligendi ipsum, iusto, praesentium sequi laborum architecto eaque est illum at. Rerum, dicta.
            Porro, natus. Corporis odit quos reiciendis? Blanditiis, obcaecati necessitatibus pariatur placeat laborum voluptatum dolorem quisquam, ducimus nobis quos earum sit quis molestias ab, at labore in. Distinctio neque quis quos!
            Saepe ab culpa dolorem est assumenda incidunt laborum, libero voluptates nam sapiente hic ullam aperiam? Reprehenderit minima non ducimus autem aliquid sit ipsa laborum tempore, debitis modi voluptate provident tenetur?
            Unde porro quaerat enim quae, recusandae id odit eos alias inventore minus voluptas iste? Modi explicabo repellendus soluta placeat dicta neque cum eaque corrupti minima vel doloribus, nihil magni delectus.
            Esse, earum neque. Deserunt est quasi mollitia eveniet iure reprehenderit ratione nam odit architecto. Dolorem ut cupiditate vero dicta, expedita animi adipisci, placeat eveniet facilis veritatis eaque minima in! Voluptatem.
            Dolore in saepe quisquam officiis delectus itaque natus esse maxime dolorum explicabo corporis, quae quasi temporibus eum laudantium doloribus deserunt accusantium repellendus minima ea dicta doloremque. Dignissimos voluptate deserunt non.
            Iure assumenda iusto, voluptatum in animi molestias similique harum dolorum amet enim atque numquam nulla doloremque sunt ducimus quisquam praesentium ipsum ullam dolor officia blanditiis repellendus pariatur. Quod, beatae nesciunt.
            Fuga enim hic sequi sint reiciendis, molestiae sed error eligendi exercitationem. Eum sit repellendus qui, id fugit, facilis non quos velit similique est sequi, consequatur vel totam quod quae hic?
            Dolorem hic ex id quam blanditiis numquam? Explicabo numquam quia dignissimos? Id nesciunt corporis facere incidunt in reiciendis fugiat ab, rem nisi nobis qui aliquid sed, error architecto quo atque.
         </p>
      </>

   );
}

export default App;